version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "spotify-tracker-sam-LambdaGetSavedTracks"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-148nh4a4hjibx"
s3_prefix = "spotify-tracker-sam-LambdaGetSavedTracks"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
