# This is a basic workflow to help you get started with Actions

name: 2-Now-Playing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [feature/*, hotfix/*]

  workflow_run:
    workflows: [1-Main-Template]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      md5hash: ${{ steps.md5.outputs.md5 }}

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::195663387853:role/github-oidc-Role-8FD7L07NDB33
          aws-region: us-east-1
      - name: Zip Code
        working-directory: ./1_NowPlaying/code
        run: zip -r ../code.zip *

      - id: md5
        name: md5 zip
        working-directory: ./1_NowPlaying
        run: |
          echo "::set-output name=md5::$(md5sum code.zip | awk '{ print $1 }')"

      - name: Upload to S3 as code.zip
        working-directory: ./1_NowPlaying/
        run: aws s3 cp code.zip s3://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f/now_playing.zip

      - name: Upload to S3 as md5
        working-directory: ./1_NowPlaying/
        run: aws s3 cp code.zip s3://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f/code/${{steps.md5.outputs.md5}}

      - name: Deploy CFT
        working-directory: ./1_NowPlaying/
        run: aws cloudformation deploy --template-file template.yaml --stack-name spotify-tracker-sam-LambdaNowPlaying-1IUKZPQTGVSC0 --capabilities CAPABILITY_IAM --force-upload --parameter-overrides Key=${{steps.md5.outputs.md5}}
